### ISSUE TITLE
可以支持一下dockerfile输入吗

### ISSUE THREAD

**Issue by schsiung** [wukongdaily/DockerTarBuilder#10]

**Comment by bl-sun** [comment]
什么是dockerfile输入？

**Comment by schsiung** [comment]
比如给根据传入的dockerfile文件链接，自动执行docker build，然后提供打包好的镜像压缩包？

**Comment by bl-sun** [comment]
听起来好像可以。不过你也可以先下载下来dockerfile里面的基础镜像

**Comment by azureology** [comment]
@schsiung 我做了一个，[试试看](https://github.com/azureology/DockerTarBuilder)?
填入包含Dockerfile的repo地址就行
