### ISSUE TITLE
请问这个报错是需要docker login吗

### ISSUE THREAD

**Issue by lecomet** [wukongdaily/DockerTarBuilder#13]
Error response from daemon: pull access denied for l4t-pytorch, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by cathy-imu** [comment]
+1

**Comment by wukongdaily** [comment]
不需要docker login，你的镜像名称和标签填写正确吗。

**Comment by wukongdaily** [comment]
要填写正确的镜像名称:标签。一般形如：作者/镜像名称:标签  举个例子，ztz1989/l4t-pytorch:latest
