### ISSUE TITLE
您好！查具体镜像显示404，无法显示具体镜像信息。

### ISSUE THREAD

**Issue by hy5528** [wukongdaily/DockerTarBuilder#16]

**Comment by wukongdaily** [comment]
镜像名称是什么

**Comment by hy5528** [comment]
好象随便一个镜像都是，如akilli/cms

**Comment by wukongdaily** [comment]
我这边可以查的呀。你那边网络出状况了吧。你看截图
![image](https://github.com/user-attachments/assets/258293d9-d8aa-4f24-b12c-75b0924e523a)

**Comment by hy5528** [comment]
点一下akilli/cms就出现404

**Comment by wukongdaily** [comment]
那就是那个代理网站出的bug。那就用原网址吧。富强访问。https://hub.docker.com/layers/akilli/cms/latest/images/sha256-d676d6222b9d270fd8828f23ca85bdf1a5c0b1e86573d4fd9b690ee049e08fee?context=explore
