### ISSUE TITLE
no space left on device Error: Process completed with exit code 1.

### ISSUE THREAD

**Issue by 663D74N** [wukongdaily/DockerTarBuilder#2]
Run images="tensorflow/tensorflow:nightly-gpu-jupyter"

write ./.docker_temp_2316002147: no space left on device
Error: Process completed with exit code 1.

[logs_25206408447.zip](https://github.com/user-attachments/files/15942241/logs_25206408447.zip)

**Comment by wukongdaily** [comment]
fixed
https://github.com/wukongdaily/DockerTarBuilder/commit/3d76d51d7995c180f48910c8abcec9f1980d38cc
