### ISSUE TITLE
可以查到镜像为什么拉取失败了

### ISSUE THREAD

**Issue by z47288** [wukongdaily/DockerTarBuilder#24]
![image](https://github.com/user-attachments/assets/d80d5f35-25be-4565-bdf2-a7930a0e0860)
![image](https://github.com/user-attachments/assets/94c39822-5b39-4b7b-9adf-b08bd9b40c69)

**Comment by wukongdaily** [comment]
https://hub.docker.com/r/sulinggg/openwrt/tags
你看一下latest这标签。它仅支持arm64平台，你的action 要确保选的是arm64平台。但根据日志 你选的是x86-64平台。作者没有开发过这个平台的镜像啊。不仅要名称正确，平台也要正确哦。
不过也是怪他弄的确实太乱了。
你应该填写 sulinggg/openwrt:amd64
或者 sulinggg/openwrt:x86_64
这些写法是根据 https://hub.docker.com/r/sulinggg/openwrt/tags 
查出来的。
